/**
 * icons.js — Central Font Awesome library registration.
 * Import this file once in index.js. All registered icons are then
 * available globally via <FontAwesomeIcon icon="..." />.
 *
 * Add icons here as the app grows. Import only what you use
 * so tree-shaking keeps the bundle lean.
 */
import { library } from '@fortawesome/fontawesome-svg-core';

// ── Solid icons ──────────────────────────────────────────────────────────────
import {
  faSackDollar,
  faMoneyBillTrendUp,
  faChartLine,
  faChartBar,
  faArrowTrendUp,
  faArrowTrendDown,
  faCircleCheck,
  faCircleXmark,
  faCircleExclamation,
  faTriangleExclamation,
  faInfoCircle,
  faCoins,
  faWallet,
  faCreditCard,
  faFileInvoiceDollar,
  faReceipt,
  faHandHoldingDollar,
  faBuildingColumns,
  faUserTie,
  faUsers,
  faGraduationCap,
  faBuilding,
  faChalkboardUser,
  faCalendarDays,
  faCalendarCheck,
  faClock,
  faClockRotateLeft,
  faHouse,
  faBars,
  faXmark,
  faAngleDown,
  faAngleUp,
  faAngleRight,
  faChevronLeft,
  faChevronRight,
  faGear,
  faUser,
  faRightFromBracket,
  faMagnifyingGlass,
  faBell,
  faPlus,
  faPencil,
  faTrash,
  faUpload,
  faDownload,
  faFilePdf,
  faEye,
  faEyeSlash,
  faCheck,
  faSpinner,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faEllipsisVertical,
  faLock,
  faUnlock,
  faStar,
  faStarHalfStroke,
  faBriefcase,
  faTag,
  faTags,
  faPercent,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faRotate,
  faCircleDot,
  faLocationDot
} from '@fortawesome/free-solid-svg-icons';

// ── Regular icons ─────────────────────────────────────────────────────────────
import {
  faClock as farClock,
  faCalendarDays as farCalendarDays,
  faCircleCheck as farCircleCheck,
  faCircleXmark as farCircleXmark,
  faUser as farUser,
  faStar as farStar,
  faFileLines,
  faEnvelope,
  faCircle
} from '@fortawesome/free-regular-svg-icons';

// ── Register all ──────────────────────────────────────────────────────────────
library.add(
  // solid
  faSackDollar,
  faMoneyBillTrendUp,
  faChartLine,
  faChartBar,
  faArrowTrendUp,
  faArrowTrendDown,
  faCircleCheck,
  faCircleXmark,
  faCircleExclamation,
  faTriangleExclamation,
  faInfoCircle,
  faCoins,
  faWallet,
  faCreditCard,
  faFileInvoiceDollar,
  faReceipt,
  faHandHoldingDollar,
  faBuildingColumns,
  faUserTie,
  faUsers,
  faGraduationCap,
  faBuilding,
  faChalkboardUser,
  faCalendarDays,
  faCalendarCheck,
  faClock,
  faClockRotateLeft,
  faHouse,
  faBars,
  faXmark,
  faAngleDown,
  faAngleUp,
  faAngleRight,
  faChevronLeft,
  faChevronRight,
  faGear,
  faUser,
  faRightFromBracket,
  faMagnifyingGlass,
  faBell,
  faPlus,
  faPencil,
  faTrash,
  faUpload,
  faDownload,
  faFilePdf,
  faEye,
  faEyeSlash,
  faCheck,
  faSpinner,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faEllipsisVertical,
  faLock,
  faUnlock,
  faStar,
  faStarHalfStroke,
  faBriefcase,
  faTag,
  faTags,
  faPercent,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faRotate,
  faCircleDot,
  faLocationDot,
  // regular
  farClock,
  farCalendarDays,
  farCircleCheck,
  farCircleXmark,
  farUser,
  farStar,
  faFileLines,
  faEnvelope,
  faCircle
);
